name: Linting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: warp-ubuntu-latest-x64-16x

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@4305c38b25d97ef35a8ad1f985ccf2d2242004f2 # stable
        with:
          toolchain: stable
          override: true
          components: rustfmt

      - name: Build
        run: cargo build --workspace --verbose

      - name: Lint
        run: cargo clippy --workspace -- -D warnings

      - name: Format code
        run: cargo fmt --all -- --check

      - name: Deny
        uses: EmbarkStudios/cargo-deny-action@30f817c6f72275c6d54dc744fbca09ebc958599f # v2.0.12

